### ISSUE TITLE
Feature Request: Turn the fan off temporarly when the HVAC system is running

### ISSUE THREAD

**Issue by haberda** [UbhiTS/ad-autofanspeed#2]
When my HVAC system is cooling, and the fan is running, it is too cold. It might be nice to have a feature that temporarily turns the fan off when the HVAC is running and then resumes when the HVAC is off.

Thanks!

**Comment by UbhiTS** [comment]
Hi, I apologize for the delay in my response. I've been tied up with personal and work issue past couple of months. I just wanted to understand the issues in a bit more detail. 

The program shuts off the fan if the temp is lower than 'low' limit. The main reason for this was that if the HVAC is running, and the room suddenly becomes too cold, then the fan turns off. Can you please give me a little more detail about your use case. I'm open to have a call if you want. You can email me @ ubhits@outlook.com to set up some time.

Again, sorry for the delay in my response.

**Comment by UbhiTS** [comment]
closing due to no response
