### ISSUE TITLE
To Celsius?

### ISSUE THREAD

**Issue by Skaveny** [UbhiTS/ad-autofanspeed#4]
How do I change from F to Celsius?

**Comment by UbhiTS** [comment]
I've never tried it myself, but I presume that it would depend on your HA units setup. I don't have any code specific to F or C, my system is setup for F, so it works with F. I think if your HA is setup for C, and you give C values in apps.yaml entry, it should work as expected. Let me know if it doesn't work and we can debug it if you want on your system.

**Comment by UbhiTS** [comment]
Did it work for you ?

**Comment by UbhiTS** [comment]
Closing cause of no response. Please feel free to reopen if you are unable to configure the app with celcius.
